name: CI de Testes do Backend

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Instalar dependências
        run: npm install
        working-directory: backend

      - name: Iniciar contêineres Docker
        run: docker compose up -d
        working-directory: backend

      - name: Aguardar o banco de dados de teste
        run: sleep 15

      - name: Rodar Testes Unitários
        run: npm run test
        working-directory: backend
      
      # --- PASSO CORRIGIDO COM VARIÁVEIS EXPLÍCITAS ---
      - name: Rodar Testes de Integração
        env:
          # Define as variáveis de ambiente diretamente para este passo
          DB_HOST: localhost
          DB_PORT: 5433
          DB_USERNAME: radical_user
          DB_PASSWORD: radical_password
          DB_DATABASE: radical_test_db
          JWT_SECRET: este_e_um_segredo_de_teste_muito_seguro
          JWT_EXPIRATION_TIME: 15m
        run: npm run test:e2e
        working-directory: backend

      - name: Parar contêineres Docker
        if: always()
        run: docker compose down
        working-directory: backend